### ISSUE TITLE
Jekyll-Pug

### ISSUE THREAD

**Issue by DougBeney** [planetjekyll/awesome-jekyll-plugins#15]
Thanks for creating this list! It's super in-depth. 

I created a Jekyll plugin for using Pug and would love to add it, but I'm not sure the best place to put it.

**Website**: http://jekyll-pug.dougie.io/
**Github**: https://github.com/DougBeney/jekyll-pug

I'm not really sure if it still qualifies as a "converter" plugin. In order to provide the best Pug experience, it overrides Jekyll's liquid rendering class, and if you look at the source code, there's quite a lot of functionality.

**Comment by geraldb** [comment]
@DougBeney  Great plugin. Love Pug. Please add it. If you don't mind the "Markup & Markdown Converters" category is a good start. Cheers.

**Comment by DougBeney** [comment]
Thanks!
