### ISSUE TITLE
jekyll-postfiles not listed

### ISSUE THREAD

**Issue by ffes** [planetjekyll/awesome-jekyll-plugins#45]
I use `jekyll-postfiles` on my blog and was a bit surprised it isn't listed on one of your great pages.
It allows you to store the files belonging to a post (like images) in the same directory as the markdown file.

https://github.com/nhoizey/jekyll-postfiles
https://rubygems.org/gems/jekyll-postfiles

**Comment by geraldb** [comment]
Thanks for highlighting the jekyll postfiles plugin. You're welcome to add the plugin to the directory.
